### ISSUE TITLE
Issue on abx_micro_poe time windows

### ISSUE THREAD

**Issue by mmr12** [alistairewj/sepsis3-mimic#11]
On line: [https://github.com/alistairewj/sepsis3-mimic/blob/master/query/tbls/abx-micro-prescription.sql#L89](url)

When setting the intervals between cultures and antibiotics, in specific looking at the 24h prior the sampling,  I disagree with the interval here:
      ```-- if charttime is not available, use chartdate
          me24.charttime is null
      and ab_tbl.antibiotic_time > me24.chartdate
      and ab_tbl.antibiotic_time <= me24.chartdate + interval '24' hour```

Say ab = 4 and me = 12,
then ab < me; this violates the first constraint (
```and ab_tbl.antibiotic_time > me24.chartdate```

hence I would have this
      ```-- if charttime is not available, use chartdate
          me24.charttime is null
      and ab_tbl.antibiotic_time > me24.chartdate - interval '24' hour
      and ab_tbl.antibiotic_time <= me24.chartdate```

**Comment by alistairewj** [comment]
In that case, `me24.chartdate` is always a date, therefore it's time
component is always 00:00:00, so the query checks if the antibiotic was
charted on the same day as the culture. It definitely would be better to
put in a date_trunc so this logic is more explicit.

The conversation is a bit mute though because there is a bug on line 76;
that line should be on line 80. As a result of that bug this clause doesn't
execute, so we essentially ignore the (admittedly small) number of cultures
which only have a date.

>

**Comment by mmr12** [comment]
Got it, thank you for the explanation!
