### ISSUE TITLE
Questions about sepsis3-cohort code

### ISSUE THREAD

**Issue by wyyyzw** [alistairewj/sepsis3-mimic#9]
Thank you for the chance to learn the sepsis 3 code. I have some queries about the exclusion criteria in sepsis3 cohort: 1. Why exclude the patients with first service in CSURG, VSURG and TSURG? 2. Why only choose the metavision database from mimic?

**Comment by alistairewj** [comment]
1. We excluded these patients as we believed they were physiologically abnormal but due to non-sepsis reasons, and we were not interested in evaluating sepsis in this subpopulation.
2. The prescriptions data is only available after 2002, so there is a fraction (1/7th) of CareVue patients who have missing data for the suspected infection definition. It was easiest to simply limit the cohort to MetaVision and avoid this issue, as the sample size was sufficient.
